Handle ReadTimeoutError when catching ES TransportErrors
When handling a `TransportError` from Elasticsearch, if the error is a
`ReadTimeoutError` it will not have the attribute `error` therefore we
get the following stack trace:

```
AttributeError: 'ReadTimeoutError' object has no attribute 'get'
```

We now catch the `AttributeError` and handle it accordingly.